namespace Server.Models;

// Mock only: there is no real AI backend yet, so Answer is a templated string generated by
// the client (NoteAiMockResponder) — this table just persists whatever it produced.
public class AiChatMessage
{
    public int Id { get; set; }

    public Guid HighlightId { get; set; }
    public NoteHighlight Highlight { get; set; } = null!;

    public required string Question { get; set; }
    public required string Answer { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
